_BASE_: "../Base_det.yaml"

MODEL:
#  WEIGHTS: "output/R50/ctw1500/pretrain_150k-tt-mlt-ic13-15_maxlen50_96voc/model_final.pth"
  WEIGHTS: "/media/WD_2T/chill_research/deepsolo/pretrain_weights/pretrain_ctw_96voc.pth"
  TRANSFORMER:
    VOC_SIZE: 96
    NUM_POINTS: 50
    LOSS:
        BEZIER_SAMPLE_POINTS: 50
        BEZIER_CLASS_WEIGHT: 1.0
        BEZIER_COORD_WEIGHT: 0.5
        POINT_CLASS_WEIGHT: 1.0
        POINT_COORD_WEIGHT: 0.5
        POINT_TEXT_WEIGHT: 1.0 #0.5
        BOUNDARY_WEIGHT: 0.25
  
DATASETS:
  TRAIN: ("ctw1500_train_96voc",)
  TEST: ("ctw1500_test",)

INPUT:
  ROTATE: False
#  MIN_SIZE_TEST: 1000
#  MAX_SIZE_TEST: 1200
  MIN_SIZE_TRAIN: (480, 576, 672, 768, 896)
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 1200

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 5e-5
  LR_BACKBONE: 5e-6
  WARMUP_ITERS: 0
  STEPS: (8000,)
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 4000

TEST:
  EVAL_PERIOD: 1000

#SOLVER:
##  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
#  LR_SCHEDULER_NAME: "WarmupCosineLR"
#  IMS_PER_BATCH: 1
#  BASE_LR: 5e-5
##  LR_BACKBONE: 5e-6
#  WARMUP_ITERS: 2000
##  STEPS: (8000,)
#  MAX_ITER: 400000
#  CHECKPOINT_PERIOD: 5000
#
#TEST:
#  EVAL_PERIOD: 10000
#  DETECTIONS_PER_IMAGE: 100
##  LEXICON_TYPE: None

OUTPUT_DIR: "output/R50/ctw1500_1"
